### ISSUE TITLE
Package for ARM64 on Raspberry Pi?

### ISSUE THREAD

**Issue by iAmSaugata** [Hulxv/vnstat-client#13]
I am not an expert in Linux, I tried to compile this in a docker container, but it get failed every time with lot's of module error, no matter what I do, result is same.

Will there be a version available for ARM64, which can be download and install directly?

Regards,
Saugata D.

**Comment by Hulxv** [comment]
Sorry about that, I'll try to provide a package for ARM64 as soon as possible.

Thanks for informing me of that.

**Comment by iAmSaugata** [comment]
> Sorry about that, I'll try to provide a package for ARM64 as soon as possible.
> 
> Thanks for informing me of that.

Thank you for your response. I will be waiting for this, my end goal is to run it in a container.

**Comment by iAmSaugata** [comment]
This is what I have done so far.

apt install npm -y
npm install -g npm
curl -o- -L https://yarnpkg.com/install.sh | bash
exec bash
git clone https://github.com/Hulxv/vnstat-client.git
cd ./vnstat-client
yarn install

> #Getting` failed at this stage
> yarn install v1.22.19
> warning package.json: License should be a valid SPDX license expression
> warning vnstat-client@22.2.11: License should be a valid SPDX license expression
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> error conf@10.1.2: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.0"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

# If I do yarn install --ignore-engines, getting many errors
>  electron-builder install-app-deps
> Error: Cannot find module 'fs/promises'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/home/pi/vnstat-client/node_modules/builder-util/src/fs.ts:5:1)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/home/pi/vnstat-client/node_modules/builder-util/src/util.ts:25:1)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
> error Command failed with exit code 1.

**Comment by Hulxv** [comment]
You need to install latest version from ```nodejs``` 

read [this](https://stackoverflow.com/questions/68085375/cannot-find-module-fs-promises-electron-js).

**Comment by iAmSaugata** [comment]
Tried that too, now greeting sql error, I guess right now it is beyond my reach to fix this.

node_modules/@vscode/sqlite3: Command failed.

**Comment by Hulxv** [comment]
Hey
Since few, I release a new version ([v22.5.28](https://github.com/Hulxv/vnstat-client/releases/tag/v22.5.28)) with packaging for arm64.
I want to make sure it works properly. So, Can you try it?

**Comment by iAmSaugata** [comment]
I will check and will update you.

**Comment by iAmSaugata** [comment]
Package required lot's of dependency, dpkg -i is not installing all the dependencies, fortunately apt now support local install.
>apt install ./vnstat-client_22.5.28_arm64.deb -y

This working, but getting error in final configuration.

>Processing triggers for libc-bin (2.31-13+deb11u3) ...
Setting up glib-networking:arm64 (2.66.0-2) ...
Setting up libsoup2.4-1:arm64 (2.72.0-2) ...
Setting up libsoup-gnome2.4-1:arm64 (2.72.0-2) ...
Setting up librest-0.7-0:arm64 (0.8.1-1.1) ...
Setting up libgtk-3-0:arm64 (3.24.24-4+deb11u2) ...
Setting up libgtk-3-bin (3.24.24-4+deb11u2) ...
Setting up libvte-2.91-0:arm64 (0.62.3-1) ...
Setting up notification-daemon (3.20.0-4) ...
Setting up vnstat-client (22.5.28) ...
**/var/lib/dpkg/info/vnstat-client.postinst: line 10: update-desktop-database: command not found**
Setting up termit (3.1-1) ...
update-alternatives: using /usr/bin/termit to provide /usr/bin/x-terminal-emulator (x-terminal-emulator) in auto mode
Processing triggers for libc-bin (2.31-13+deb11u3) ...
Removing intermediate container c6df2f46fcb3

**Comment by Hulxv** [comment]
is the issue solved?

**Comment by Hulxv** [comment]
You take a lot of time without any response, So I close your issue.
If there is still any problem, You can tell me.
