### ISSUE TITLE
Support for Flatpak/Snap/Appimage

### ISSUE THREAD

**Issue by dtantono** [Hulxv/vnstat-client#14]
to cover wider distributions. Is it possible to get this app in Flatpak/Snap/Appimage?

**Comment by Hulxv** [comment]
You will find Appimage package [here](https://github.com/Hulxv/vnstat-client/releases/tag/v22.5.28).
But flatpack/snap isn't available yet.
In the future, Maybe I will provide them.

**Comment by Hulxv** [comment]
Your issue will be closed, If there is any question, You can open a new issue with that question.

I hope I helped you.
