### ISSUE TITLE
user monthly history page

### ISSUE THREAD

**Issue by jacktar2022** [Hulxv/vnstat-client#19]
First month user. month has just changed to august. cannot see previous months usage history. cannot find any referral on the main toolbar menu. 
current page shows only This month     current use  and Yesterday.   
Month button only shows current date/month.  ideally this would show previous months in calendar form, so that you can choose which month you want to view.

**Comment by Hulxv** [comment]
It's a bug or feature needed?

**Comment by jacktar2022** [comment]
OK.. it was a feature needed... but it can be found by using dropdown on the "Monthly" button... which then shows the "yearly" usage - by month .
Case Closed 
Thanks
