### ISSUE TITLE
AppImage Not Found

### ISSUE THREAD

**Issue by SupremeJA** [Hulxv/vnstat-client#39]
Following the installation guide I clicked on the AppImage link but it led me to a github 404 page, I also tried copying the installation code into my terminal but I got a 404 error as well.

![Screenshot from 2024-09-30 03-40-08](https://github.com/user-attachments/assets/17fe70e4-c2cc-44d4-8fea-ef0a4f2f582b)

![image](https://github.com/user-attachments/assets/ce5cda2e-0006-494f-a009-ceb10512ab53)

**Comment by hulxv** [comment]
You should replace `x.y.z` with the version that you want to install.
You can install the latest release from [here](https://github.com/hulxv/vnstat-client/releases/download/v22.5.28/vnstat-client-22.5.28.AppImage)
Or for installing it via `wget`:
```terminal
wget https://github.com/hulxv/vnstat-client/releases/download/v22.5.28/vnstat-client-22.5.28.AppImage
```

**Comment by hulxv** [comment]
I believe your issue is resolved. If you encounter any further issues, please don't hesitate to let us know.

**Comment by SupremeJA** [comment]
Yes, it has been resolved. Thanks
